export const products = [
  {
    categoryId: 1,
    name: "Small Ecru Ceramic Compote",
    imgUrl: "/products/1.jpg",
    images: [
      "/products/2.jpg",
      "/products/3.jpg",
      "/products/4.jpg",
      "/products/5.jpg",
      "/products/6.jpg",
    ],
    color: [
      { name: "#a1b8be" },
      { name: "#fff" },
      { name: "#c88242" },
      { name: "#212f39" },
      { name: "#dcb9a8" },
      { name: "#a7b2a3" },
    ],
    price: 49,
    text: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit.",
  },
  {
    categoryId: 1,
    name: 'Warrick White Vase 14"',
    imgUrl: "/products/2.jpg",
    images: [
      "/products/1.jpg",
      "/products/3.jpg",
      "/products/4.jpg",
      "/products/5.jpg",
      "/products/6.jpg",
    ],
    color: [
      { name: "#a1b8be" },
      { name: "#fff" },
      { name: "#c88242" },
      { name: "#212f39" },
      { name: "#dcb9a8" },
      { name: "#a7b2a3" },
    ],
    price: 49,
    text: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit tortor eu.",
  },
  {
    categoryId: 2,
    name: "Porcelain Dinner Plate",
    imgUrl: "/products/3.jpg",
    images: [
      "/products/2.jpg",
      "/products/1.jpg",
      "/products/4.jpg",
      "/products/5.jpg",
      "/products/6.jpg",
    ],
    color: [
      { name: "#a1b8be" },
      { name: "#fff" },
      { name: "#c88242" },
      { name: "#212f39" },
      { name: "#dcb9a8" },
      { name: "#a7b2a3" },
    ],
    price: 49,
    text: "Lorem ipsum dolor sit amet conse bolli tetur.",
  },
  {
    categoryId: 2,
    name: "Warrick White Vase 20",
    imgUrl: "/products/4.jpg",
    images: [
      "/products/2.jpg",
      "/products/3.jpg",
      "/products/1.jpg",
      "/products/5.jpg",
      "/products/6.jpg",
    ],
    color: [
      { name: "#a1b8be" },
      { name: "#fff" },
      { name: "#c88242" },
      { name: "#212f39" },
      { name: "#dcb9a8" },
      { name: "#a7b2a3" },
    ],
    price: 49,
    text: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit tortor eu.",
  },
  {
    categoryId: 3,
    name: "Rounded Dual Handled Vase",
    imgUrl: "/products/5.jpg",
    images: [
      "/products/2.jpg",
      "/products/3.jpg",
      "/products/4.jpg",
      "/products/1.jpg",
      "/products/6.jpg",
    ],
    color: [
      { name: "#a1b8be" },
      { name: "#fff" },
      { name: "#c88242" },
      { name: "#212f39" },
      { name: "#dcb9a8" },
      { name: "#a7b2a3" },
    ],
    price: 49,
    text: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit tortor eu.",
  },
  {
    categoryId: 3,
    name: "Marin White Dinner Plate",
    imgUrl: "/products/6.jpg",
    images: [
      "/products/2.jpg",
      "/products/3.jpg",
      "/products/4.jpg",
      "/products/5.jpg",
      "/products/1.jpg",
    ],
    color: [
      { name: "#a1b8be" },
      { name: "#fff" },
      { name: "#c88242" },
      { name: "#212f39" },
      { name: "#dcb9a8" },
      { name: "#a7b2a3" },
    ],
    price: 49,
    text: "Lorem ipsum dolor sit amet conse.",
  },
  {
    categoryId: 4,
    name: "Tall Cream Ceramic Vase",
    imgUrl: "/products/7.jpg",
    images: [
      "/products/2.jpg",
      "/products/3.jpg",
      "/products/4.jpg",
      "/products/5.jpg",
      "/products/6.jpg",
    ],
    color: [
      { name: "#a1b8be" },
      { name: "#fff" },
      { name: "#c88242" },
      { name: "#212f39" },
      { name: "#dcb9a8" },
      { name: "#a7b2a3" },
    ],
    price: 49,
    text: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit.",
  },
  {
    categoryId: 4,
    name: "Luana Bowl",
    imgUrl: "/products/8.jpg",
    images: [
      "/products/2.jpg",
      "/products/3.jpg",
      "/products/4.jpg",
      "/products/5.jpg",
      "/products/6.jpg",
    ],
    color: [
      { name: "#a1b8be" },
      { name: "#fff" },
      { name: "#c88242" },
      { name: "#212f39" },
      { name: "#dcb9a8" },
      { name: "#a7b2a3" },
    ],
    price: 49,
    text: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit tortor eu.",
  },
  {
    categoryId: 5,
    name: "Porcelain Dinner Plate",
    imgUrl: "/products/9.jpg",
    images: [
      "/products/2.jpg",
      "/products/3.jpg",
      "/products/4.jpg",
      "/products/5.jpg",
      "/products/6.jpg",
    ],
    color: [
      { name: "#a1b8be" },
      { name: "#fff" },
      { name: "#c88242" },
      { name: "#212f39" },
      { name: "#dcb9a8" },
      { name: "#a7b2a3" },
    ],
    price: 49,
    text: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit tortor eu.",
  },
  {
    categoryId: 5,
    name: "Ophelia Matte Natural  Vase",
    imgUrl: "/products/10.jpg",
    images: [
      "/products/2.jpg",
      "/products/3.jpg",
      "/products/4.jpg",
      "/products/5.jpg",
      "/products/6.jpg",
    ],
    color: [
      { name: "#a1b8be" },
      { name: "#fff" },
      { name: "#c88242" },
      { name: "#212f39" },
      { name: "#dcb9a8" },
      { name: "#a7b2a3" },
    ],
    price: 49,
    text: "Lorem ipsum dolor sit amet conse bolli tetur.",
  },
  {
    categoryId: 5,
    name: "Porcelain Dinner Plate",
    imgUrl: "/products/11.jpg",
    images: [
      "/products/2.jpg",
      "/products/3.jpg",
      "/products/4.jpg",
      "/products/5.jpg",
      "/products/6.jpg",
    ],
    color: [
      { name: "#a1b8be" },
      { name: "#fff" },
      { name: "#c88242" },
      { name: "#212f39" },
      { name: "#dcb9a8" },
      { name: "#a7b2a3" },
    ],
    price: 49,
    text: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit tortor eu.",
  },
  {
    categoryId: 4,
    name: "Luana Bowl",
    imgUrl: "/products/12.jpg",
    images: [
      "/products/2.jpg",
      "/products/3.jpg",
      "/products/4.jpg",
      "/products/5.jpg",
      "/products/6.jpg",
    ],
    color: [
      { name: "#a1b8be" },
      { name: "#fff" },
      { name: "#c88242" },
      { name: "#212f39" },
      { name: "#dcb9a8" },
      { name: "#a7b2a3" },
    ],
    price: 49,
    text: "Lorem ipsum dolor sit amet conse.",
  },
];

export const productIdes = products.map((el, i) => ({
  ...el,
  color: el.color.map((c, i) => ({ ...c, id: i + 1 })),
  id: i + 1,
}));
